# Generated by Django 4.2.20 on 2025-05-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_image_edited_image_edited_contour_contourpoint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contourpoint',
            options={'ordering': ['contour_id', 'order']},
        ),
        migrations.AddField(
            model_name='contourpoint',
            name='contour_id',
            field=models.IntegerField(default=0, help_text='ID контура (для поддержки множественных контуров)'),
        ),
    ]
