# Generated by Django 4.2.20 on 2025-05-24 10:07

from django.db import migrations, models
import images.models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_alter_contourpoint_options_contourpoint_contour_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='contour_mask',
            field=models.FileField(blank=True, null=True, upload_to=images.models.user_directory_path),
        ),
    ]
